import os
from dotenv import load_dotenv
load_dotenv() # Load variables from a .env file
"""
Django settings for projectX project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# BASE_DIR: Represents the base directory of your Django project.
# __file__: Refers to the path of the current file (settings.py).
# .resolve(): Resolves any symbolic links to get the absolute path.
# .parent: Moves one level up in the directory structure. We do this twice to get to the project root.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# These settings are for development and should be carefully configured for production environments.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY: A randomly generated string used for cryptographic signing.
# It's crucial for security, especially for session management and CSRF protection.
# **Never share your SECRET_KEY and keep it secret in production!**
SECRET_KEY = 'django-insecure-)=q0@1*b$k=2ez44+fb5x3j7$06z0)cd7j&zcj%0url&i!uqjh'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG: A boolean indicating whether the application is in debug mode.
# When True, Django will show detailed error pages, which is helpful during development.
# **Set this to False in production for security and performance reasons.**
DEBUG = True

# ALLOWED_HOSTS: A list of strings representing the host/domain names that this Django site can serve.
# It prevents HTTP Host header attacks. In production, you should list your actual domain names and IPs.
ALLOWED_HOSTS = ['*']
# Tells Django to look for this header to know if the request is HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition
# INSTALLED_APPS: A list of strings naming all the Django applications that are active in this project.
# Django comes with several built-in apps (like admin, auth, etc.), and you'll add your own here.
INSTALLED_APPS = [
    'admin_tools_stats', # This is a third-party app that provides statistical insights and visualizations for the Django admin interface. It can help you analyze data and monitor the performance of your application directly from the admin dashboard.
    'django_nvd3', # This is a third-party app for rendering NVD3 charts in Django templates. It allows you to create interactive charts using the NVD3 JavaScript library, which is built on top of D3.js. This can be particularly useful for visualizing weather data in your application.
    "unfold", # This is custom admin panel extension for dajngo this help to imporve the quality of work flow
    'customadmin.apps.CustomadminConfig', # Your 'customadmin' application. The '.apps.CustomadminConfig' specifies the configuration class.
    'user.apps.UserConfig',              # Your 'user' application. The '.apps.UserConfig' specifies the configuration class.
    'main.apps.MainConfig',              # Your 'services' application. The '.apps.ServicesConfig' specifies the configuration class.
    'django.contrib.admin',              # Django's administrative interface.
    'django.contrib.auth',               # Django's authentication and authorization system.
    'django.contrib.contenttypes',       # A framework for handling content types in Django.
    'django.contrib.sessions',           # Django's session management system.
    'django.contrib.messages',           # A framework for displaying temporary messages to users.
    'django.contrib.staticfiles',        # For managing static files like CSS, JavaScript, and images.
]

# MIDDLEWARE: A list of middleware classes that are executed in order for each request and response in your Django application.
# Middleware can perform various tasks like security checks, session handling, and request/response processing.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',            # Provides security enhancements.
    'django.contrib.sessions.middleware.SessionMiddleware',     # Enables session support.
    'django.middleware.common.CommonMiddleware',                # Performs various common tasks like URL normalization.
    'django.middleware.csrf.CsrfViewMiddleware',                # Protects against cross-site request forgery attacks.
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Associates users with requests using sessions.
    'django.contrib.messages.middleware.MessageMiddleware',     # Enables message support.
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # Protects against clickjacking attacks.
]

# ROOT_URLCONF: A string representing the Python module that contains the project's main URL configurations (typically 'projectX.urls').
ROOT_URLCONF = 'projectX.urls'

# TEMPLATES: A list of dictionaries defining how Django should load and render templates.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Specifies the template engine to use.
        'DIRS': [],  # A list of directories where Django should look for templates in addition to app directories.
        'APP_DIRS': True,  # Tells Django to look for templates within the 'templates' subdirectory of each installed app.
        'OPTIONS': {
            'context_processors': [
                # Context processors are functions that add variables to the context dictionary when a template is rendered.
                'django.template.context_processors.request',  # Makes the HttpRequest object available in templates.
                'django.contrib.auth.context_processors.auth',    # Adds user-related variables (e.g., {{ user }}).
                'django.contrib.messages.context_processors.messages',  # Makes messages available in templates.
            ],
        },
    },
]

# WSGI_APPLICATION: A string pointing to the WSGI () application object that Django uses to communicate with your web server.
WSGI_APPLICATION = 'projectX.wsgi.application'

# Color band for unfold admin panel extension
UNFOLD = {
    "COLORS": {
        "primary": {
            "50": "250 245 255",   # Decimal RGB values
            "100": "243 232 255",
            "200": "233 213 252",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",   # Core accent color
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASES: A dictionary containing the configuration for your project's database connections.
# The 'default' key represents the primary database connection.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'weather_application_database',
        'USER': 'priyanshu',
        'PASSWORD': 'PaPe11good',
        'HOST': 'localhost',  # or your PostgreSQL server IPWeb Server Gateway Interface
        'PORT': '5432',       # default PostgreSQL port
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_api_cache",  # The name of the SQL table Django will create
        "TIMEOUT": 600,                  # Default expiration time in seconds (10 mins)
        "OPTIONS": {
            "MAX_ENTRIES": 500000         # Maximum number of keys before purging old ones
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS: A list of dictionaries specifying the password validation rules that Django will enforce.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Checks for similarity to user attributes.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Enforces a minimum password length.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Checks against a list of common passwords.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Checks if the password is entirely numeric.
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# These settings control Django's internationalization and localization features.
LANGUAGE_CODE = 'en-in' 

TIME_ZONE = 'Asia/Kolkata'  # The default time zone for the project (set to India Standard Time).

USE_I18N = True  # A boolean indicating whether Django's internationalization system is enabled.

USE_TZ = True    # A boolean indicating whether Django should use time-zone-aware datetimes.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL: The base URL to serve static files from (e.g., in templates, you'd refer to CSS as '/static/style.css').
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# DEFAULT_AUTO_FIELD: Specifies the default primary key field type for automatically created models.
# BigAutoField is a 64-bit integer, providing more flexibility for large datasets.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = "login"