# Generated by Django 5.2.1 on 2026-06-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usersettings_delete_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
